# Generated by Django 2.2.3 on 2019-07-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
