# Generated by Django 2.2.3 on 2019-07-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
